version: '3.8'

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    environment:
      RUST_LOG: 'info'
      ENV: '${ENV}'
      POSTGRES_USER: '${POSTGRES_USER}'
      POSTGRES_PASSWORD: '${POSTGRES_PASSWORD}'
      POSTGRES_DB: '${POSTGRES_DB}'
      APP_WEB_ADDR: '0.0.0.0:8080'
      APP_POSTGRES_DSN: 'postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@postgres:5432/${POSTGRES_DB}'
      APP_POSTGRES_MAX_CONNS: '10'
      APP_TOKEN_JWT_SECRET_KEY: '${APP_TOKEN_JWT_SECRET_KEY}'
      APP_TOKEN_ACCESS_TOKEN_DURATION_DAYS: '7'
      APP_TOKEN_REFRESH_TOKEN_DURATION_DAYS: '30'
      APP_TOKEN_PHONE_CODE_TTL_MINUTES: '2'
      APP_TOKEN_ACCESS_TOKEN_SET_PASSWORD_MINUTES: '30'
      APP_TWILIO_ACCOUNT_SID: '${APP_TWILIO_ACCOUNT_SID}'
      APP_TWILIO_AUTH_TOKEN: '${APP_TWILIO_AUTH_TOKEN}'
      APP_TWILIO_FROM_NUMBER: '${APP_TWILIO_FROM_NUMBER}'
      ZALO_APP_ID: '${ZALO_APP_ID}'
      ZALO_APP_SECRET_KEY: '${ZALO_APP_SECRET_KEY}'
    ports:
      - '8080:8080'
    depends_on:
      postgres:
        condition: service_healthy

  postgres:
    image: postgres:15-alpine
    environment:
      POSTGRES_USER: '${POSTGRES_USER}'
      POSTGRES_PASSWORD: '${POSTGRES_PASSWORD}'
      POSTGRES_DB: '${POSTGRES_DB}'
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}']
      interval: 5s
      timeout: 5s
      retries: 5
    ports:
      - '5432:5432'

volumes:
  pgdata:
