[package]
name = "utils"
version = "0.1.0"
edition = "2021"

[dependencies]
argon2 = "0.5.3"
rand = "0.9.0"
rand_core = "0.6.4"
serde.workspace = true
serde_json.workspace = true
async-trait = "0.1"
#Member
core_app = { path = "../core_app" }
